version: 2
updates:
  - package-ecosystem: gradle
    commit-message:
      prefix: "ci(deps)"
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    commit-message:
      prefix: "ci(deps)"
    directory: /
    schedule:
      interval: weekly
